import { boolean, pgTable, text, uuid } from "drizzle-orm/pg-core";
import { createdBy, softDelete, timestamps } from "../../db/columns.js";

/** Table speakers — generated by the scaffolder from the `@repo/schemas` entity. */
export const speakers = pgTable("speakers", {
  id: uuid("id").defaultRandom().primaryKey(),
  fullName: text("full_name").notNull(),
  email: text("email").notNull(),
  bio: text("bio"),
  company: text("company"),
  website: text("website"),
  isConfirmed: boolean("is_confirmed").notNull().default(false),
  ...timestamps,
  ...softDelete,
  ...createdBy,
});
