import { z } from "zod";
import type { Db } from "../../db/client.js";
import {
  BadRequestError,
  ConflictError,
  NotFoundError,
  UnprocessableEntityError,
} from "../../lib/http/problem.js";
import { paginate } from "../../lib/http/pagination.js";
import {
  type CreateTalkInEventSchema,
  type CreateTalkSchema,
  type TalkListQuery,
  type UpdateTalkSchema,
} from "./talks.dto.js";
import { eventsRepository } from "../events/events.repository.js";
import { roomsRepository } from "../rooms/rooms.repository.js";
import { talksRepository } from "./talks.repository.js";
import { intervalContains, intervalsOverlap } from "./talks.rules.js";

type CreateInput = z.infer<typeof CreateTalkSchema>;
type UpdateInput = z.infer<typeof UpdateTalkSchema>;
type CreateInEventInput = z.infer<typeof CreateTalkInEventSchema>;

/** The full set of values needed to check the scheduling rules (after merging on edit). */
interface ScheduledTalk {
  eventId: string;
  roomId: string;
  startsAt: Date;
  endsAt: Date;
}

interface ScheduleCheckOptions {
  /** The id of the talk being edited — excluded from the clash search so it cannot clash with itself. */
  exceptId?: string;
  /** A message prefix, "Prelekcja 2" say — during bulk creation it points at the position in the batch. */
  label?: string;
}

/**
 * The domain rules for talks. They need to read other records, so they can NOT live in the Zod
 * schema (which sees only the payload and is shared with the frontend) — see
 * `docs/dx-pilot/conference.md`.
 */
async function assertSchedule(
  db: Db,
  values: ScheduledTalk,
  { exceptId, label }: ScheduleCheckOptions = {},
): Promise<void> {
  const prefix = label ? `${label}: ` : "";
  // The order of checks: relations first, rules second — otherwise we would be asking for the time
  // window of an event that does not exist.
  const event = await eventsRepository.findById(db, values.eventId);
  if (!event) {
    throw new BadRequestError(`${prefix}wskazana relacja (eventId) nie istnieje.`);
  }
  const room = await roomsRepository.findById(db, values.roomId);
  if (!room) {
    throw new BadRequestError(`${prefix}wskazana relacja (roomId) nie istnieje.`);
  }

  // `UpdateTalkSchema` is `schema.partial()`, so the entity's cross-field `refine` does NOT apply to
  // PATCH — we check the ordering of the times here so both paths behave the same.
  if (values.endsAt <= values.startsAt) {
    throw new UnprocessableEntityError(
      `${prefix}koniec prelekcji musi być późniejszy niż jej początek.`,
    );
  }

  if (!intervalContains(event, values)) {
    throw new UnprocessableEntityError(
      `${prefix}prelekcja musi mieścić się w oknie czasowym wydarzenia.`,
      {
        eventStartsAt: event.startsAt,
        eventEndsAt: event.endsAt,
      },
    );
  }

  // `event.venueId` is optional (required only at publication) — while the event has no venue there
  // is nothing to enforce.
  if (event.venueId && room.venueId !== event.venueId) {
    throw new UnprocessableEntityError(
      `${prefix}sala musi należeć do obiektu, w którym odbywa się wydarzenie.`,
    );
  }

  const clash = await talksRepository.findOverlappingInRoom(db, { ...values, exceptId });
  if (clash) {
    throw new ConflictError(
      `${prefix}sala jest w tym czasie zajęta przez prelekcję „${clash.title}".`,
    );
  }
}

/** Business logic for talks. Generated by the scaffolder plus the scheduling rules (added by hand). */
export const talksService = {
  async list(db: Db, query: TalkListQuery) {
    const { items, total } = await talksRepository.list(db, query);
    return paginate(items, total, query);
  },

  async getById(db: Db, id: string) {
    const row = await talksRepository.findById(db, id);
    if (!row) {
      throw new NotFoundError("Talk nie istnieje.");
    }
    return row;
  },

  async create(db: Db, input: CreateInput, createdById: string) {
    await assertSchedule(db, input);
    return talksRepository.create(db, { ...input, createdBy: createdById });
  },

  /**
   * Creates several talks of one event at once (the wizard's "agenda" step).
   *
   **All-or-nothing** semantics: the rules are checked for every entry first, and only then a
   * single `INSERT` runs. That way a batch with one clash never leaves half the talks in the
   * database. Clashes are computed in two places because they have two sources: SQL sees the rows
   * already stored, while the loop below sees the entries from this batch that are not there yet.
   */
  async createManyForEvent(
    db: Db,
    eventId: string,
    inputs: CreateInEventInput[],
    createdById: string,
  ) {
    const event = await eventsRepository.findById(db, eventId);
    if (!event) {
      throw new NotFoundError("Event nie istnieje.");
    }

    const accepted: ScheduledTalk[] = [];
    const values = inputs.map((input, index) => {
      const candidate = { ...input, eventId };
      const label = `Prelekcja ${index + 1} („${input.title}")`;
      return { candidate, label };
    });

    for (const { candidate, label } of values) {
      await assertSchedule(db, candidate, { label });
      const clash = accepted.find(
        (earlier) => earlier.roomId === candidate.roomId && intervalsOverlap(earlier, candidate),
      );
      if (clash) {
        throw new ConflictError(`${label}: koliduje z inną prelekcją z tej samej paczki.`);
      }
      accepted.push(candidate);
    }

    return talksRepository.createMany(
      db,
      values.map(({ candidate }) => ({ ...candidate, createdBy: createdById })),
    );
  },

  async update(db: Db, id: string, input: UpdateInput) {
    // PATCH is partial, so the rules are checked on the values AFTER merging with the current row —
    // changing only the room still has to be verified against the existing times.
    const current = await talksRepository.findById(db, id);
    if (!current) {
      throw new NotFoundError("Talk nie istnieje.");
    }
    await assertSchedule(
      db,
      {
        eventId: input.eventId ?? current.eventId,
        roomId: input.roomId ?? current.roomId,
        startsAt: input.startsAt ?? current.startsAt,
        endsAt: input.endsAt ?? current.endsAt,
      },
      { exceptId: id },
    );

    const updated = await talksRepository.update(db, id, input);
    if (!updated) {
      throw new NotFoundError("Talk nie istnieje.");
    }
    return updated;
  },

  async remove(db: Db, id: string) {
    const deleted = await talksRepository.softDelete(db, id);
    if (!deleted) {
      throw new NotFoundError("Talk nie istnieje.");
    }
  },
};
