import { pgTable, text, uuid } from "drizzle-orm/pg-core";
import { createdBy, softDelete, timestamps } from "../../db/columns.js";

/** Table venues — generated by the scaffolder from the `@repo/schemas` entity. */
export const venues = pgTable("venues", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  city: text("city").notNull(),
  address: text("address"),
  ...timestamps,
  ...softDelete,
  ...createdBy,
});
